# Generated by Django 4.1.1 on 2022-10-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=16)),
                ('senha', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=45)),
                ('nomeloja', models.CharField(max_length=45)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
    ]
